# Generated by Django 5.1 on 2025-10-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('vat_id', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.company')),
            ],
            options={
                'unique_together': {('company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Other', 'Other')], default='Other', max_length=50)),
                ('service_tag', models.CharField(max_length=120, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('action_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('done', 'Zakończone')], default='open', max_length=50)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_actions', to='inventory.computer')),
            ],
            options={
                'ordering': ['-action_date', '-id'],
            },
        ),
    ]
