# Generated by Django 5.1 on 2025-10-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Komputer', 'verbose_name_plural': 'Komputery'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='serviceaction',
            options={'ordering': ['-action_date', '-id'], 'verbose_name': 'Akcja serwisowa', 'verbose_name_plural': 'Akcje serwisowe'},
        ),
    ]
