# Generated by Django 5.1 on 2025-10-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='inventory.company'),
        ),
    ]
